
# GTK_THEME=Adwaita-dark
QT_QPA_PLATFORMTHEME=qt6ct # for activate kvantum style&theme
QT_STYLE_OVERRIDE=kvantum # for activate kvantum style&theme
QT_AUTO_SCREEN_SCALE_FACTOR=1

# wayland / nvidia
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
